# Form implementation generated from reading ui file 'costsGui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import csv
from costs import LaborCosts
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.textInput = QtWidgets.QLineEdit(parent=Form)
        self.textInput.setGeometry(QtCore.QRect(170, 40, 113, 21))
        self.textInput.setObjectName("textInput")
        self.textInput_2 = QtWidgets.QLineEdit(parent=Form)
        self.textInput_2.setGeometry(QtCore.QRect(170, 110, 113, 21))
        self.textInput_2.setObjectName("textInput_2")
        self.button = QtWidgets.QPushButton(parent=Form)
        self.button.setGeometry(QtCore.QRect(40, 110, 100, 32))
        self.button.setObjectName("button")
        self.button.clicked.connect(self.clicked)
        self.output = QtWidgets.QTextEdit(parent=Form)
        self.output.setGeometry(QtCore.QRect(90, 160, 181, 111))
        self.output.setObjectName("output")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def clicked(self):
        salesfname = self.textInput.text()
        timecardsfname = self.textInput_2.text()
        salesFname = salesfname.replace('\n','')
        timecardsFname = timecardsfname.replace('\n','')

        costData = LaborCosts(salesFname,timecardsFname)
        net = costData.strArray[0]
        laborTotal = costData.strArray[1]
        laborPlRent = costData.strArray[2]
        laborTotalPercent = costData.strArray[3]
        laborPlRentPercent = costData.strArray[4]


        self.output.append("Dreadlock net (includes 10% cash sales estimate for stubbys)")
        self.output.append(net)
        self.output.append('')
        self.output.append('Labor cost (just time cards)')
        self.output.append(laborTotal)
        self.output.append('')
        self.output.append('Labor cost percent (just timecards)')
        self.output.append(laborTotalPercent)
        self.output.append('')
        self.output.append('Labor cost (timecards and rent)')
        self.output.append(laborPlRent)
        self.output.append('')
        self.output.append('Total Labor Cost Percent (timecards and rent)')
        self.output.append(laborPlRentPercent)
        self.output.append('')

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button.setText(_translate("Form", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
