# Form implementation generated from reading ui file 'LaborCost.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QFileDialog
import csv
from costs import LaborCosts


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.button = QtWidgets.QPushButton(parent=Form)
        self.button.setGeometry(QtCore.QRect(80, 70, 100, 32))
        self.button.setObjectName("button")
        self.button.clicked.connect(self.clicked1)
        self.button_2 = QtWidgets.QPushButton(parent=Form)
        self.button_2.setGeometry(QtCore.QRect(80, 120, 100, 32))
        self.button_2.setObjectName("button_2")
        self.button_2.clicked.connect(self.clicked2)
        self.output = QtWidgets.QTextEdit(parent=Form)
        self.output.setGeometry(QtCore.QRect(200, 60, 181, 111))
        self.output.setObjectName("output")
        self.button_3 = QtWidgets.QPushButton(parent=Form)
        self.button_3.setGeometry(QtCore.QRect(230, 190, 100, 32))
        self.button_3.setObjectName("button_3")
        self.button_3.clicked.connect(self.clicked3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.timecardsFname = ''
        self.salesFname = ''

    def clicked1(self):
        _translate = QtCore.QCoreApplication.translate
        file = QFileDialog.getOpenFileName(parent= None, caption = "Open File", directory = "", filter= "All Files (*);;Python Files (*.py)")
        self.timecardsFname = file[0]

        self.button.setText(_translate("Form", 'Uploaded'))


        print(self.timecardsFname)

    def clicked2(self):
        _translate = QtCore.QCoreApplication.translate
        file = QFileDialog.getOpenFileName(parent= None, caption = "Open File", directory = "", filter= "All Files (*);;Python Files (*.py)")
        self.salesFname = file[0]

        self.button_2.setText(_translate("Form", 'Uploaded'))

        print(self.salesFname)

    def clicked3(self):
        if (self.timecardsFname != '') and (self.salesFname != ''):

            costData = LaborCosts(self.salesFname, self.timecardsFname)
            net = costData.strArray[0]
            laborTotal = costData.strArray[1]
            laborPlRent = costData.strArray[2]
            laborTotalPercent = costData.strArray[3]
            laborPlRentPercent = costData.strArray[4]
            employeesMissing = costData.strArray[5]

            self.output.append('The following employees were not found:')
            self.output.append(employeesMissing)
            self.output.append("Dreadlock net (includes 10% cash sales estimate for stubbys)")
            self.output.append(net)
            self.output.append('')
            self.output.append('Labor cost (just time cards)')
            self.output.append(laborTotal)
            self.output.append('')
            self.output.append('Labor cost percent (just timecards)')
            self.output.append(laborTotalPercent)
            self.output.append('')
            self.output.append('Labor cost (timecards and rent)')
            self.output.append(laborPlRent)
            self.output.append('')
            self.output.append('Total Labor Cost Percent (timecards and rent)')
            self.output.append(laborPlRentPercent)
            self.output.append('')
        else:
            print('files not uploaded yet')



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button.setText(_translate("Form", "TimeCards File"))
        self.button_2.setText(_translate("Form", "Sales File"))
        self.button_3.setText(_translate("Form", "Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
