# Form implementation generated from reading ui file 'laborCostGui2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QFileDialog
import csv
from laborCostsByLocation import LaborCosts


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(651, 526)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(220, 60, 311, 361))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.output = QtWidgets.QTextEdit(parent=self.widget)
        self.output.setObjectName("output")
        self.verticalLayout_4.addWidget(self.output)
        self.button_3 = QtWidgets.QPushButton(parent=self.widget)
        self.button_3.setObjectName("button_3")
        self.verticalLayout_4.addWidget(self.button_3)
        self.button_3.clicked.connect(self.clicked3)
        self.button_4 = QtWidgets.QPushButton(parent=self.widget)
        self.button_4.setObjectName("button_4")
        self.verticalLayout_4.addWidget(self.button_4)
        # self.button_4.clicked.connect(self.clicked4)
        self.widget1 = QtWidgets.QWidget(parent=Form)
        self.widget1.setGeometry(QtCore.QRect(40, 130, 151, 162))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.stubbysBox = QtWidgets.QCheckBox(parent=self.widget1)
        self.stubbysBox.setObjectName("stubbysBox")
        self.stubbysBox.stateChanged.connect(self.stubbysChecked)
        self.verticalLayout.addWidget(self.stubbysBox)
        self.scootersBox = QtWidgets.QCheckBox(parent=self.widget1)
        self.scootersBox.setObjectName("scootersBox")
        self.scootersBox.stateChanged.connect(self.scootersChecked)
        self.verticalLayout.addWidget(self.scootersBox)
        self.icBox = QtWidgets.QCheckBox(parent=self.widget1)
        self.icBox.setObjectName("icBox")
        self.icBox.stateChanged.connect(self.icChecked)
        self.verticalLayout.addWidget(self.icBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button = QtWidgets.QPushButton(parent=self.widget1)
        self.button.setObjectName("button")
        self.button.clicked.connect(self.clicked1)
        self.verticalLayout_2.addWidget(self.button)
        self.button_2 = QtWidgets.QPushButton(parent=self.widget1)
        self.button_2.setObjectName("button_2")
        self.verticalLayout_2.addWidget(self.button_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.button_2.clicked.connect(self.clicked2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.timecardsFname = ''
        self.salesFname = ''

        self.checkArray = [False, False, False]

    def stubbysChecked(self):

        self.checkArray[0] = self.stubbysBox.isChecked()
        print(self.checkArray)

    def scootersChecked(self):
        self.checkArray[1] = self.scootersBox.isChecked()
        print(self.checkArray)

    def icChecked(self):
        self.checkArray[2] = self.icBox.isChecked()
        print(self.checkArray)

    def clicked1(self):
        _translate = QtCore.QCoreApplication.translate
        file = QFileDialog.getOpenFileName(parent= None, caption = "Open File", directory = "", filter= "All Files (*);;Python Files (*.py)")
        self.timecardsFname = file[0]

        self.button.setText(_translate("Form", 'Uploaded'))


        print(self.timecardsFname)

    def clicked2(self):
        _translate = QtCore.QCoreApplication.translate
        file = QFileDialog.getOpenFileName(parent= None, caption = "Open File", directory = "", filter= "All Files (*);;Python Files (*.py)")
        self.salesFname = file[0]

        self.button_2.setText(_translate("Form", 'Uploaded'))

        print(self.salesFname)

    def clicked3(self):

        if any(self.checkArray):
            if (self.timecardsFname != '') and (self.salesFname != ''):

                costData = LaborCosts(self.salesFname, self.timecardsFname, self.checkArray)
                laborArray = costData.laborCostArray
                locationNet = costData.locationNet
                locRatio = costData.locationLaborCostPercent
                net = costData.strArray[0]
                laborTotal = costData.strArray[1]
                laborPlRent = costData.strArray[2]
                laborTotalPercent = costData.strArray[3]
                laborPlRentPercent = costData.strArray[4]
                employeesMissing = costData.strArray[5]

                if employeesMissing !='':
                    self.output.append('The following employees were not found:')
                    self.output.append(employeesMissing)

                # CHANGE OUTPUT FOR BY LOCATION


                self.output.append("Dreadlock net (includes 10% cash sales estimate for stubbys)")
                self.output.append(net)
                self.output.append('')

                self.output.append('Labor cost (just time cards)')
                self.output.append(laborTotal)
                self.output.append('')
                self.output.append('Labor cost percent (just timecards)')
                self.output.append(laborTotalPercent)
                self.output.append('')
                self.output.append('Labor cost (timecards and rent)')
                self.output.append(laborPlRent)
                self.output.append('')
                self.output.append('Total Labor Cost Percent (timecards and rent)')
                self.output.append(laborPlRentPercent)
                self.output.append('')
                self.output.append('')
                self.output.append('')
                if self.checkArray[0]:
                    self.output.append('Stubbys (no rent)')
                    self.output.append('Net Sales ' + str(locationNet[0]))
                    self.output.append('Labor ' + str(laborArray[0]))

                    self.output.append('Percent ' + str(locRatio[0]))
                    self.output.append('')
                if self.checkArray[1]:
                    self.output.append('Scooters (no rent)')
                    self.output.append('Net Sales ' + str(locationNet[1]))
                    self.output.append('Labor ' + str(laborArray[1]))

                    self.output.append('Percent ' + str(locRatio[1]))
                    self.output.append('')

                if self.checkArray[2]:
                    self.output.append('Island Coffee (no rent)')
                    self.output.append('Net Sales ' + str(locationNet[2]))
                    self.output.append('Labor ' + str(laborArray[2]))

                    self.output.append('Percent ' + str(locRatio[2]))


            else:
                print('files not uploaded yet')
        else:
            print(('Must Choose Atleast One Location'))


    #______ADD EMPLOYEE BREAKDOWN______________________



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_3.setText(_translate("Form", "Run"))
        self.button_4.setText(_translate("Form", "Show Employee Breakdown"))
        self.label.setText(_translate("Form", "Select Locations"))
        self.stubbysBox.setText(_translate("Form", "Stubbys"))
        self.scootersBox.setText(_translate("Form", "Scooters"))
        self.icBox.setText(_translate("Form", "Island Coffee"))
        self.button.setText(_translate("Form", "TimeCards File"))
        self.button_2.setText(_translate("Form", "Sales Summary File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
